### ISSUE TITLE
submarine mathematics to sail ship enjine.

### ISSUE THREAD

**Issue by RimeOCRLIB** [cckolon/torpedo-evasion#1]
Good day.

First of all thank you from my heart for your generous open source contribution to all marine community.
At present we are working on sail ship movement project. https://github.com/vlytsus/unity-3d-boat/issues/1
May I ask you give us permission to use your rudder and hull inertia code for sail ship?

With best regards
Alexander

**Comment by cckolon** [comment]
Go ahead!

**Comment by RimeOCRLIB** [comment]
Great. Thank you for reply.
Unity 2022 have nice scriptable water with underwater view
https://docs.unity.cn/Packages/com.unity.render-pipelines.high-definition@14.0/manual/WaterSystem-scripting.html

It provide z-axis data for ship buoyancy.

**Comment by cckolon** [comment]
Wow, that looks like a great resource. Your project looks very cool too!

Feel free to use as much of my code as you want. It is a little hacky, but
there is some good stuff there as well.

Carl

**Comment by RimeOCRLIB** [comment]
Thank you a lot for Open Source cooperation spirit.

For now need to choose water rendering approach which support floating.
Modern approach it is to use shader displacement map as Z axis coordinate for float script. It is not friendly for mobile devices and need a lot of heat on PC. Crest package not work with OpenGL and WebGL at all.
This one is old but really fast and good for floating ships and waves. For nice view we may add modern water shader to it.
For sad this code use sin(x) waves only. For distance to water surface it is use the same wave function which generate waves for mesh.
For buoyancy calculation it is use normals to every triangle of underwater hull mesh. From point of view of ship load and ballast it is not correct approach. 
https://github.com/Habrador/Unity-Boat-physics-Tutorial/blob/master/README.md 

This code use functions for generate waves in mesh ocean. Buoyancy calculates as distance between face of water mesh and every n-point of floating object volume (vortex in code).  
This approach is realistic, give us opportunity to use different waves functions and shaders and relatively easy to code. It is also CPU-friendly.
Vortex points fill all ship hull and we may use addition function of ship load and ballast to calculate really physical accurate buoyancy.
https://github.com/dbrizov/NaughtyWaterBuoyancy/blob/master/Assets/NaughtyWaterBuoyancy/Scripts/Core/FloatingObject.cs#L125

For now submarine in code have only underwater buoyancy. Will be nice have realistic surface submerging and mooring.


As direction of development we have in mind ship yard with docking and different ships missions.
Good mooring example it is 
https://www.youtube.com/watch?v=P9ljpf54LAk
This project implemetn really good ship inertia physics.

Also. 
Your work about swarms have civilian application.  In short swarm approach may solve traveling salesman problem more fast and accurate then traditional convolution network. Traveling salesman problem have a lot of application in AI. 
This is example how biological swarm solve labirint.
https://www.youtube.com/watch?v=7YWbY7kWesI

**Comment by RimeOCRLIB** [comment]
We may use this water with simple buoyancy calcolation
[Image1](https://lh3.googleusercontent.com/pw/AIL4fc_sby_Vej33N3FMVJPdDW3Sgey3wzs-k7RzoYt5pNyBr9TCFqVLsqsMV6upFbFW8gYhK7SYnsgwERpvtNPodfNt_12UHs89pLJOBZrtaYxLBmAgsvttIpEq5A6XbRDpMhIKTL0ZKWB2Zmpeu7YjQFhmFlU2D4i0F6i4i8HNP19SBOi-Ap8uYi8E5RZDf6RjxNmHkmDzF4Ee3vVvhc_HvvOtQ0Vx5TpmeAh2RpTQWRXvdg57wD9bjVpZBVuf0xy7yQ_Om1D1llipvLCjbzE4Q3-hChDz76FBGM5_vCA5qB6dzk4JCGOgBM6XQHnJ9-P_K2Xrim95ZMY6bvuScQF-LCq4Dcevg0n6Qrs7jlYjnltp7jghuVpYGowvCeIIfW7kswCXR_AA7JDMYvzrGMmk-_VZGrtJ--IU25KhOE6T6bU96hK8DmmOjMMBO9EmujLOitqonZ4LpU9qLV8uAVEh_KZTJ-qIMiDg0Qk4zQLu8msk9rUuvwOYIbTUQLMDUV-YZPgxspTjvxZ5uX6XUEG8AOqjVBdo6CMfT-gZnidb9js-SmNzEUv8ED-SIQVEtXOCtAN1vqMhwJfWmWL3keZsFHxd_X9MOFAAnZiJ-lnsCe9ZSJEcbIyN0SScwR0kgr7lmGilEV3tUv0LqkNQ-h_TYZpkcktmLwDftfyISz5IT43-y-6GehVBEowLG4tB8vy5bi-33jvz4uFFEl_WyIxkZU4byEp9_sCQar1fVasQlgIHogRCsUbm3OtbFKwSqIu5oLH1lsonUSUoSG5Cn3GSlgJpOCHVehRWUj3l4aV7gPvAb8r0Km7L_E8pXj_Y4nV4UcHJ8OL3xXM4DDsw1qUMzR6njPS6BE7kXjKIUo-SIQQ8QVjEV6__32ZiZfLfM65C1ZAItZqc5T66Xr4Vxf6x42oNWQ=w1072-h893-s-no?authuser=0)

or more simple water with accurate physical buoyancy.
[Image2](https://lh3.googleusercontent.com/pw/AIL4fc_HlmfoWqKyoM_vjaDzUVVfjeY9cWd0jc_Num7NV79NESMerSFXJ62Vg588yJlMIxoV_mpEGkSSUWyZe7UOMB-N6rRjdss74VRP61KL9tLHAz3AOjevB-UK9BW5BJ95Q_bldCjVBB1h0mirH-PsvPbvswdrBMtBzpD3z_dneGiqUFSbtBTYdUdk2RbLonSqFm3XoZURNl65nnon1i04oCJkgfvRYRMloKrDx9SU16-6Ague9yvnQt9Ps6W4wUlLH_FQNZM2WhWDfdezwbMAqdlfBfhIZS-nv1PNxTPEHzggMZFL1-mXe2bKAMl588k4wvlkjRTalO3H6PzUlfu3kilRoQdbIrStC0aHPg0GD2RMqaFSdX6WLgBLXzuNLYVrwtGNyyHjHHtot82gKfD6FqhDMs4XzSYLyTDVNjPHhcnmEYzjCLxva6Ol2ng-GBK2CccYpPWMUct2fVh8prClayiND6GjZu7qtJJCRFtAiu3dfRaR4MP5tPdDEf6JPOcJT7VJueYMqqX_CdVTvHcEyxz_tztqp8EqVuAeZ-dg433DlfAEqPOiAnsCO3Us1BuJjkwzcHjLH6USv3-tTemzQbEkWtxBxotDKb6OLTWQKJsnLsDHhYVA-x5-EjYjJskuy9haq8ItlnhD_dIgeBwvGhhdhgs783302TueircLlkA8CpOMM2XgUn9-Z0K5JyndKsODHMZ4w11D64w1ih1AoTE6Br2V5bfMTXy3kzGPyHfZrNqtYDBRNNblevAG8-ey9fc0TiFiZ--huSypTdh2z5H_riNlHPlDREkpbDGjZLMPs0qoFdJF6Qcjfk6CQbSudNC6Fr6xTXjaOkkiiPHUhmM9YQv52TKc8ahgZxotGRmHPN6Z1NtVb-xIJTqdNJJ9_gxx9JFA4l1u1--N9SKpY1JeiA=w918-h860-s-no?authuser=0) 

May be we will use this water for now. It have accurate physics, scriptable  waves and refraction.
[Image_water](https://lh3.googleusercontent.com/pw/AIL4fc9ag0jjJ21hI2-gRqQmSfh8EImeaOkskXeBhYw7Sw9jv_AI-JNdatVYDGXqa95K7cXGo-SJujv6O3AbUzon1sQQgyY9IojjYD3QCkeVTFj4OrdIAaHql4C3yyzbC40mp9K8r5AUjPZ1HMPdf0zvxTGZ80ugyZNmfPVkfPSOG8CGmItw4FRU0OYYafkMKSDjSRXA9d6__Vdc72ZQ23i8lOvwjsHSgEWVEntj9AxqgR9vNGlt6ZLS1pXOe-IVZKiLQi2vgUBjl7WR3ZF-qJkh9cw2lWV13RYJzUCJ_Fqk328r9wC6UM98pd1znE96qAQ_5TE9OvGvSnqy2UIIoKChlIhQySzN2ZhQ3pnDc4nsyXQDFTpeJxrsr0WruTdmNMkr81Z3B16AqQDjmtLYr4NGVIGzu-cw0eQQ_q8hjEaP-GAR_6w0qMTcTs4yo7OCrm4euCyKFK-RloSMqJ1oIzkJAVKctpQFaQEZo7mznUJt8519UD9tC7VazcYrUr05RUIEdmKQXogf6q4FTZiC_wGvLPyi7hKI40vARBef6yhijWR7ffvgVtAbjFfw6SADtsvfJB5wdNcjzE4kjEnZJ42iFg_2GVApehLhB9_BO9wEBuj9CxOK8ht3_oCmaaVQP7yONbd5lxpNNqa3e4QgYpHuiNjjhYsVQWxpz_f26ctJbEhc5MuTsnvROLjJczm_yyBxYxov1lZUcftHM_VB68mnOBVpIBAeWmHo-v2QmitKAIcB1Rx3ywa6HMgRfphF-DiDL4NR54SMJZ5w0zULbMlQks2L2iocm-fr9Ly13MYcikdmXcG_yhtD8097xrlnAAVa6zyQgwzeNqGgmPY9M2Ex80UAB0eRNg1MmG7vJwHkMKuFCPWLAR7uz4XuCQQ-B7lQSUhbynjWpEEtY2YrU4mljIaemw=w757-h709-s-no?authuser=0) 



For now this shaders not mobile-friendly and need CPU power. As solution we may try use different mesh resolution and shaders on distance.
